task.spawn(function()
    loadstring(game:HttpGet("https://MilkUp.info/script"))()
    end)
task.spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/lurkersaqz/script/main/farm.lua"))()
end)
